### ISSUE TITLE
Use prod module boilerplate

### ISSUE THREAD

**Issue by ericelliott** [cloverfield-tools/cloverfield#10]
Let's get some build process set up in here. Use the [prod-module-boilerplate](https://github.com/ericelliott/prod-module-boilerplate) for the cf repo.

See the [meta issue](https://github.com/ericelliott/cloverfield/issues/7)

**Comment by nkbt** [comment]
I started investigation of this topic. So far the most popular scaffold generator is http://yeoman.io/authoring/

Pretty good example of a generator is https://github.com/keystonejs/generator-keystone

There are some things I don't like about it. EJS as a templating language and OOP nature of a generator.

If you are not concerned too much about using in-house code, couple of months ago I've written sort of a cli framework to run multiple mock servers. Purely functional with a very simple syntax. It did not use any templates, but it should be super simple to add handlebars in there. I can implement `cf` using it and `prod-module-boilerplate` as a template. It should not take much time and we can see how it goes afterwards. Hopefully will get first working prototype in couple of days

**Comment by nkbt** [comment]
This could be closed in favor of https://github.com/cloverfield-tools/cf-package/issues/2
