### ISSUE TITLE
Auto-scan for globally installed scaffolds

### ISSUE THREAD

**Issue by ericelliott** [cloverfield-tools/cloverfield#13]
Cloverfield should be able to detect any globally installed scaffolds.

@nkbt Could you accept your repo invite so that I can assign issues to you? =)

**Comment by nkbt** [comment]
That should be possible.

**Comment by nkbt** [comment]
Just to be clear we want to search for globally installed packages with `cf-` prefix? I'd suggest to also search for keyword `cloverfield-scaffold` or by combination of keywords `cloverfield` + `scaffold`.

**Comment by ericelliott** [comment]
:+1:
