### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by ericelliott** [cloverfield-tools/cloverfield#23]
We need to apply the contributing guide from [prod-module-boilerplate](https://github.com/cloverfield-tools/prod-module-boilerplate/blob/master/docs/contributing/index.md) to this repo. Be sure to change the repository name in the guide.

**Comment by davegomez** [comment]
I can do this if you guys are ok with it.

**Comment by nkbt** [comment]
@davegomez, thanks!
