### ISSUE TITLE
babel-core dependency not installed

### ISSUE THREAD

**Issue by davegomez** [cloverfield-tools/cloverfield#27]
The `babel-core` peer dependency needed by `babel-plugin-object-assign` won't be automatically installed anymore by npm.

For newer versions of nom this dependency must be included explicitly in the `package.json` file.

    npm WARN peerDependencies The peer dependency babel-core@>=5.6.0 included from babel-plugin-object-assign will no
    npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
    npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

**Comment by nkbt** [comment]
This is not an issue, it is a feature of new npm. Developer should decide which version to install, not the lib maintainer. PeerDependency becomes "consultative" rather then mandatory.

By the way `babel-plugin-object-assign` can be removed and `Object.assign` can be replaced with object spread, see https://twitter.com/nkbtnk/status/629475691067641856

I am closing this issue. Feel free to reopen if you have any other concerns on the topic.
