### ISSUE TITLE
Search for packages locally

### ISSUE THREAD

**Issue by nkbt** [cloverfield-tools/cloverfield#33]
At the moment Cloverfield searches for globally installed packages. We need to search for locally installed as well.

**Comment by ericelliott** [comment]
:+1:

**Comment by nkbt** [comment]
After some code written and some additional thoughts, I believe for `cloverfield` we should stick to locally installed modules exclusively. And if necessary install missing scaffolds on-demand [#17].

Technically it would simplify the code a little bit - I would be able to do simple `require(package.name)` and then run it. Without any additional parsing of `package.json`.  

But what is more important, it would be conceptually more correct - whatever `cloverfield` is working with is only stored locally, so it does not try to go beyond its own folder.

I will still make a PR with what is done, and we can update it later.

**Comment by nkbt** [comment]
See #34. It works fine for now, but I would think about removing `findGlobal` (not 100% sure on that though)

**Comment by ericelliott** [comment]
:+1:
