### ISSUE TITLE
What are your thoughts on JS Standard ? 

### ISSUE THREAD

**Issue by gaboesquivel** [cloverfield-tools/cloverfield#35]
I think Feross has [made a point on javascript standards](http://standardjs.com/)
The philosophy behind it perfectly aligns with cloverfields. 
_"No decisions to make. No .eslintrc, .jshintrc, or .jscsrc files to manage. It just works."_
NPM uses it [npm/package.json#L187](https://github.com/npm/npm/blob/master/package.json#L187)

**Comment by ericelliott** [comment]
No. For one thing, it's not an idiomatic standard. It's pretty comical to call it "standard style" and then adopt unpopular rules like "no semicolons". I like semicolon-free style, but I'd prefer to embrace idiomatic style and avoid the arguments.

For another thing, we're using ES6 rules that are not included in "standard style".

**Comment by nkbt** [comment]
@gaboesquivel its feature is a misleading name, it is way too far from "standard".  "Standard" is just another opinionated toolset with good marketing. Check out this discussion.

https://github.com/feross/standard/issues/78#issuecomment-85660078

airbnb/javascript is the one you could call mostly reasonable "standard" instead ;)

It is not a matter of personal preference it is a matter of best practices and statistics (actually, what is the most common use for this or that "feature").

**Comment by ericelliott** [comment]
:clap:
